version: '3.8'

services:
  # Serviço da aplicação Laravel
  rifa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel

  # Serviço do banco de dados MySQL
  mysql:
    image: mysql:5.7
    container_name: laravel_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: rifa
      MYSQL_USER: rifa
      MYSQL_PASSWORD: senha
    networks:
      - laravel
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: rifa # Altere para o usuário que você configurou
      PMA_PASSWORD: senha # Altere para a senha do usuário que você configurou
    networks:
      - laravel

  # Serviço do Nginx para expor o app na porta 80
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - rifa
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql-data:
    driver: local
