version: '3.8'

services:
  # Serviço da aplicação Laravel
  rifa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel

  # Serviço do banco de dados MySQL
  mysql:
    image: mysql:5.7
    container_name: laravel_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: morango3214
      MYSQL_DATABASE: gabrielaramire
      MYSQL_USER: gabrielaramire
      MYSQL_PASSWORD: morango3214
    networks:
      - laravel
    volumes:
      - mysql-data:/var/lib/mysql

  # Serviço do Nginx para expor o app na porta 80
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "10000:10000"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql-data:
    driver: local
