services:
  - type: web
    name: rifa-service
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase: mysql
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: rifa
      - key: DB_USERNAME
        value: rifa
      - key: DB_PASSWORD
        sync: false
