name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Ajuste para a versão do PHP que você está usando

    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer
        composer --version

    - name: Install PHP Dependencies
      run: |
        composer install --no-dev --optimize-autoloader

    - name: Add SSH known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 34.123.197.10 >> ~/.ssh/known_hosts

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy via SSH
      run: |
            rsync -avz --delete --exclude='.git' --exclude='node_modules' --exclude='.env' ./ gabriela_cacto@34.123.197.10:/var/www/html
   
    - name: Run Laravel migrations
      run: |
        php artisan migrate

    - name: Start Laravel Server
      run: |
        nohup php artisan serve --host=0.0.0.0 --port=3000 > server.log 2>&1 &