name: Start

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: php artisan serve
      run: |
            cd /var/www/html
            php artisan serve --host=0.0.0.0 --port=3000

